site_name: "{{cookiecutter.project_name}}"
theme:
  name: material
  analytics:
    gtag: {{cookiecutter.google_analytics_gtag}}
#  palette:
#    scheme: slate
#    primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
#  - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://{{cookiecutter.github_org}}.github.io/{{cookiecutter.project_name}}
repo_url: https://github.com/{{cookiecutter.github_org}}/{{cookiecutter.project_name}}
